base_url = "https://testzorax.github.io/"
title = "optozorax.blog"
description = "Мои програмульки и результаты их работы"
default_language = "ru"
output_dir = "docs"
compile_sass = true
minify_html = false # todo change to `true`
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
	{name = "tags"},
]
build_search_index = false
ignored_content = ["static/youtube/*.json"]

[markdown]
highlight_code = true
highlight_theme = "cheerfully-light"

##### dark
# highlight_theme = "agola-dark"
# highlight_theme = "dracula"
# highlight_theme = "monokai"
# highlight_theme = "visual-studio-dark"

##### light
# highlight_theme = "idle"
# highlight_theme = "ayu-light"
# highlight_theme = "demain"
# highlight_theme = "dimmed-fluid"
# highlight_theme = "inspired-github"
# highlight_theme = "subway-madrid"
# highlight_theme = "subway-moscow"

[extra]
name = "optozorax.blog"
after_title = " — Блог optozorax'а"
domain = "optozorax.github.io"
twitter_creator_username = "optozorax"
author = "optozorax"
header_paths = ["/", "/e", "/tags", "/about"]
header_titles = ["Блог", "Систематизация", "Теги", "Обо мне"]
show_debug = false
enable_metrica = false

[extra.social]
github = "optozorax"
tg_channel = "optozorax_dev"
youtube = "optozorax"
email = "optozorax@gmail.com"
