base_url = "https://optozorax.github.io/"
title = "optozorax.blog"
description = "Мои програмульки и результаты их работы"
default_language = "ru"
output_dir = "docs"
compile_sass = true
minify_html = false
generate_feed = true
feed_filename = "atom.xml"
taxonomies = [
	{name = "tags"},
]
build_search_index = false
ignored_content = ["static/youtube/*.json"]

[markdown]
highlight_code = true
highlight_theme = "cheerfully-light"

[extra]
name = "optozorax.blog"
after_title = " — Блог optozorax'а"
domain = "optozorax.github.io"
twitter_creator_username = "optozorax"
author = "optozorax"
header_paths = ["/", "/e", "/tags", "/about"]
header_titles = ["Блог", "Систематизация", "Теги", "Обо мне"]
show_debug = false
enable_metrika = true

[extra.social]
github = "optozorax"
tg_channel = "optozorax_dev"
youtube = "optozorax"
email = "optozorax@gmail.com"
